Add portuguese translation
MycroftAI/skill-media pull request #1
Opened 2017-09-05 16:29 UTC by 00tiagopolicarpo00

Add portuguese translation

2017-09-07 21:27 UTC, augustnmonteiro requested changes

2017-09-07 21:27 UTC, augustnmonteiro commented on vocab/pt-pt/PrevKeyword.voc
> +anterior faixa
in this case will be `faixa anterior` but I'd add `musica anterior` too

2017-09-07 21:29 UTC, augustnmonteiro requested changes

2017-09-07 21:29 UTC, augustnmonteiro commented on vocab/pt-pt/NextKeyword.voc
> +próxima faixa
I'd add `proxima musica` too

2017-09-07 21:29 UTC, augustnmonteiro commented on vocab/pt-pt/CurrentlyPlayingKeyword.voc
> +o que está reproduzir
Add `o que estou ouvindo` too

2017-09-07 21:29 UTC, augustnmonteiro commented on vocab/pt-pt/ResumeKeyword.voc
> +
add `play`

2017-09-07 21:29 UTC, augustnmonteiro commented on vocab/pt-pt/PlayKeyword.voc
> +reproduzir
add `play`

2018-02-08 05:29 UTC, penrods commented
@augustnmonteiro I'm going to go ahead and merge these -- better than not having them.  You can add your suggestions in a follow-up PR.

2018-02-08 05:29 UTC, merged